(* Auto-generated by mirari; if you edit by hand you may lose your changes. *)


let get = function Some x -> x | None -> failwith "Bad IP!"
let ip = `IPv4 (
  get (Net.Nettypes.ipv4_addr_of_string "10.0.0.2"),
  get (Net.Nettypes.ipv4_addr_of_string "255.255.255.0"),
  [get (Net.Nettypes.ipv4_addr_of_string "10.0.0.1")]
)

let main () =
  Net.Manager.create (fun mgr interface id ->
    Net.Manager.configure interface ip >>
    Testvm.main mgr interface id
  )

let () = OS.Main.run (main ())
